# name_look_up
name_look_up <- tibble::tribble(
  ~name_old, ~name_new,
  "Phengaris arion", "Maculinea arion"
) %>%  
  tibble::deframe() %>% 
  as.list()

# code_look_up
code_look_up <- tibble::tribble(
  ~code_old, ~code_new,
  "S6265", "S1058"
) %>%  
  tibble::deframe() %>% 
  as.list()

# notes_species_look_up
notes_species_look_up <- tibble::tribble(
  ~reporting_code,                                                                               ~field_label,            ~entity_table_name,
  "1.4",                                                 "1.4 Alternative species scientific name",                "data_species",
  "1.5",                                                                         "1.5 Common name",                "data_species",
  "2.1",                                                                   "2.1 Sensitive species",                "data_species",
  "2.2",                                                                      "2.2 Year or Period",                "data_species",
  "2.3",                                                                    "2.3 Distribution map",                "data_species",
  "2.4",                                                       "2.4 Distribution map; Method used",                "data_species",
  "2.5",                                                                     "2.5 Additional maps",                "data_species",
  "3.1",                                          "3.1 Is the species take in the wild/ exploited",         "data_species_annexV",
  "3.2",                                   "3.2 Which of the measures in Art. 14 have been taken?",         "data_species_annexV",
  "3.3",      "3.3 Hunting bag or quantity taken in the wild for Mammals and Acipenseridae (Fish)",         "data_species_annexV",
  "3.4",                               "3.4 Hunting bag or quantity take in the wild; Method used",         "data_species_annexV",
  "3.5",                                                              "3.5 Additional information",         "data_species_annexV",
  "4.1",                             "4.1 Biogeographic or marine region where the species occurs",        "data_species_regions",
  "4.2",                                                              "4.2 Sources of information",        "data_species_regions",
  "5.1",                                                                        "5.1 Surface area",        "data_species_regions",
  "5.2",                                                            "5.2 Short term trend; Period",        "data_species_regions",
  "5.3",                                                         "5.3 Short term trend; Direction",        "data_species_regions",
  "5.4",                                                         "5.4 Short term trend; Magnitude",        "data_species_regions",
  "5.5",                                                       "5.5 Short term trend; Method used",        "data_species_regions",
  "5.6",                                                             "5.6 Long term trend; Period",        "data_species_regions",
  "5.7",                                                          "5.7 Long term trend; Direction",        "data_species_regions",
  "5.8",                                                          "5.8 Long term trend; Magnitude",        "data_species_regions",
  "5.9",                                                        "5.9 Long term trend; Method used",        "data_species_regions",
  "5.10",                                                         "5.10 Favourable reference range",        "data_species_regions",
  "5.11",                              "5.11 Change and reason for change in surface area of range",                 "data_change",
  "5.12",                                                             "5.12 Additional information",        "data_species_regions",
  "6.1",                                                                      "6.1 Year or Period",        "data_species_regions",
  "6.2",                                                                     "6.2 Population size",        "data_species_regions",
  "6.3",                                                                    "6.3 Type of estimate",        "data_species_regions",
  "6.4",                                                          "6.4 Additional population size",        "data_species_regions",
  "6.5",                                                                    "6.5 Type of estimate",        "data_species_regions",
  "6.6",                                                        "6.6 Population size; Method used",        "data_species_regions",
  "6.7",                                                            "6.7 Short term trend; Period",        "data_species_regions",
  "6.8",                                                         "6.8 Short term trend; Direction",        "data_species_regions",
  "6.9",                                                         "6.9 Short term trend; Magnitude",        "data_species_regions",
  "6.10",                                                       "6.10 Short term trend; Method used",        "data_species_regions",
  "6.11",                                                            "6.11 Long term trend; Period",        "data_species_regions",
  "6.12",                                                         "6.12 Long term trend; Direction",        "data_species_regions",
  "6.13",                                                         "6.13 Long term trend; Magnitude",        "data_species_regions",
  "6.14",                                                       "6.14 Long term trend; Method used",        "data_species_regions",
  "6.15",                                                    "6.15 Favourable reference population",        "data_species_regions",
  "6.16",                                    "6.16 Change and reason for change in population size",                 "data_change",
  "6.17",                                                             "6.17 Additional information",        "data_species_regions",
  "7.1",                                 "7.1 Sufficiency of area and quality of occupied habitat",        "data_species_regions",
  "7.2",                    "7.2 Sufficiency of area and quality of occupied habitat; Method used",        "data_species_regions",
  "7.3",                                                            "7.3 Short term trend; Period",        "data_species_regions",
  "7.4",                                                         "7.4 Short term trend; Direction",        "data_species_regions",
  "7.5",                                                       "7.5 Short term trend; Method used",        "data_species_regions",
  "7.6",                                                             "7.6 Long term trend; Period",        "data_species_regions",
  "7.7",                                                          "7.7 Long term trend; Direction",        "data_species_regions",
  "7.8",                                                        "7.8 Long term trend; Method used",        "data_species_regions",
  "7.9",                                                              "7.9 Additional information",        "data_species_regions",
  "8.1",                                              "8.1 Characterisation of pressures/ threats",      "data_pressures_threats",
  "8.2",                                                              "8.2 Sources of information", "data_pressures_threats_info",
  "8.3",                                                              "8.3 Additional information", "data_pressures_threats_info",
  "9.1",                                                                  "9.1 Status of measures",          "data_measures_info",
  "9.2",                                                  "9.2 Main purpose of the measures taken",          "data_measures_info",
  "9.3",                                                      "9.3 Location of the measures taken",          "data_measures_info",
  "9.4",                                                            "9.4 Response to the measures",          "data_measures_info",
  "9.5",                                                  "9.5 List of main conservation measures",               "data_measures",
  "9.6",                                                              "9.6 Additional information",          "data_measures_info",
  "10.1",                                                     "10.1 Future prospects of parameters",        "data_species_regions",
  "10.2",                                                             "10.2 Additional information",        "data_species_regions",
  "11.1",                                                                              "11.1 Range",        "data_species_regions",
  "11.2",                                                                         "11.2 Population",        "data_species_regions",
  "11.3",                                                            "11.3 Habitat for the species",        "data_species_regions",
  "11.4",                                                                   "11.4 Future prospects",        "data_species_regions",
  "11.5",                                          "11.5 Overall assessment of Conservation Status",        "data_species_regions",
  "11.6",                                               "11.6 Overall trend in Conservation Status",        "data_species_regions",
  "11.7", "11.7 Change and reasons for change in conservation status and conservation status trend",                 "data_change",
  "11.8",                                                             "11.8 Additional information",        "data_species_regions",
  "12.1",                            "12.1 Population size inside the pSCIs, SCIs and SACs network",        "data_species_regions",
  "12.2",                                                                   "12.2 Type of estimate",        "data_species_regions",
  "12.3",                                    "12.3 Population size inside the network; Method used",        "data_species_regions",
  "12.4",              "12.4 Short term trend of the population size within the network; Direction",        "data_species_regions",
  "12.5",                "12.5 Short term trend of population size within the network; Method used",        "data_species_regions",
  "12.6",                                                             "12.6 Additional information",        "data_species_regions",
  "13.1",                                           "13.1 Justification of 1% threshold for trends",        "data_species_regions",
  "13.2",                                                          "13.2 Trans-boundary assessment",        "data_species_regions",
  "13.3",                                                         "13.3 Other relevant information",        "data_species_regions"
)