# name_look_up
name_look_up <- tibble::tribble(
  ~name_old, ~name_new,
  "Phengaris arion", "Maculinea arion"
) %>%  
  tibble::deframe() %>% 
  as.list()

# code_look_up
code_look_up <- tibble::tribble(
  ~code_old, ~code_new,
  "S6265", "S1058"
) %>%  
  tibble::deframe() %>% 
  as.list()

# notes_species_look_up
notes_species_look_up <- tibble::tribble(
  ~reporting_code,                                                                               ~field_label,            ~entity_table_name,
  "1.4",                                                 "1.4 Alternative species scientific name",                "data_species",
  "1.5",                                                                         "1.5 Common name",                "data_species",
  "2.1",                                                                   "2.1 Sensitive species",                "data_species",
  "2.2",                                                                      "2.2 Year or Period",                "data_species",
  "2.3",                                                                    "2.3 Distribution map",                "data_species",
  "2.4",                                                       "2.4 Distribution map; Method used",                "data_species",
  "2.5",                                                                     "2.5 Additional maps",                "data_species",
  "3.1",                                          "3.1 Is the species take in the wild/ exploited",         "data_species",
  "3.2",                                   "3.2 Which of the measures in Art. 14 have been taken?",         "data_species",
  "3.3",      "3.3 Hunting bag or quantity taken in the wild for Mammals and Acipenseridae (Fish)",         "data_species",
  "3.4",                               "3.4 Hunting bag or quantity take in the wild; Method used",         "data_species",
  "3.5",                                                              "3.5 Additional information",         "data_species",
  "4.1",                             "4.1 Biogeographic or marine region where the species occurs",        "data_species_regions",
  "4.2",                                                              "4.2 Sources of information",        "data_species_regions",
  "5.1",                                                                        "5.1 Surface area",        "data_species_regions",
  "5.2",                                                            "5.2 Short term trend; Period",        "data_species_regions",
  "5.3",                                                         "5.3 Short term trend; Direction",        "data_species_regions",
  "5.4",                                                         "5.4 Short term trend; Magnitude",        "data_species_regions",
  "5.5",                                                       "5.5 Short term trend; Method used",        "data_species_regions",
  "5.6",                                                             "5.6 Long term trend; Period",        "data_species_regions",
  "5.7",                                                          "5.7 Long term trend; Direction",        "data_species_regions",
  "5.8",                                                          "5.8 Long term trend; Magnitude",        "data_species_regions",
  "5.9",                                                        "5.9 Long term trend; Method used",        "data_species_regions",
  "5.10",                                                         "5.10 Favourable reference range",        "data_species_regions",
  "5.11",                              "5.11 Change and reason for change in surface area of range",                 "data_species_regions",
  "5.12",                                                             "5.12 Additional information",        "data_species_regions",
  "6.1",                                                                      "6.1 Year or Period",        "data_species_regions",
  "6.2",                                                                     "6.2 Population size",        "data_species_regions",
  "6.3",                                                                    "6.3 Type of estimate",        "data_species_regions",
  "6.4",                                                          "6.4 Additional population size",        "data_species_regions",
  "6.5",                                                                    "6.5 Type of estimate",        "data_species_regions",
  "6.6",                                                        "6.6 Population size; Method used",        "data_species_regions",
  "6.7",                                                            "6.7 Short term trend; Period",        "data_species_regions",
  "6.8",                                                         "6.8 Short term trend; Direction",        "data_species_regions",
  "6.9",                                                         "6.9 Short term trend; Magnitude",        "data_species_regions",
  "6.10",                                                       "6.10 Short term trend; Method used",        "data_species_regions",
  "6.11",                                                            "6.11 Long term trend; Period",        "data_species_regions",
  "6.12",                                                         "6.12 Long term trend; Direction",        "data_species_regions",
  "6.13",                                                         "6.13 Long term trend; Magnitude",        "data_species_regions",
  "6.14",                                                       "6.14 Long term trend; Method used",        "data_species_regions",
  "6.15",                                                    "6.15 Favourable reference population",        "data_species_regions",
  "6.16",                                    "6.16 Change and reason for change in population size",                 "data_species_regions",
  "6.17",                                                             "6.17 Additional information",        "data_species_regions",
  "7.1",                                 "7.1 Sufficiency of area and quality of occupied habitat",        "data_species_regions",
  "7.2",                    "7.2 Sufficiency of area and quality of occupied habitat; Method used",        "data_species_regions",
  "7.3",                                                            "7.3 Short term trend; Period",        "data_species_regions",
  "7.4",                                                         "7.4 Short term trend; Direction",        "data_species_regions",
  "7.5",                                                       "7.5 Short term trend; Method used",        "data_species_regions",
  "7.6",                                                             "7.6 Long term trend; Period",        "data_species_regions",
  "7.7",                                                          "7.7 Long term trend; Direction",        "data_species_regions",
  "7.8",                                                        "7.8 Long term trend; Method used",        "data_species_regions",
  "7.9",                                                              "7.9 Additional information",        "data_species_regions",
  "8.1",                                              "8.1 Characterisation of pressures/ threats",      "data_species_regions",
  "8.2",                                                              "8.2 Sources of information", "data_species_regions",
  "8.3",                                                              "8.3 Additional information", "data_species_regions",
  "9.1",                                                                  "9.1 Status of measures",          "data_species_regions",
  "9.2",                                                  "9.2 Main purpose of the measures taken",          "data_species_regions",
  "9.3",                                                      "9.3 Location of the measures taken",          "data_species_regions",
  "9.4",                                                            "9.4 Response to the measures",          "data_species_regions",
  "9.5",                                                  "9.5 List of main conservation measures",               "data_species_regions",
  "9.6",                                                              "9.6 Additional information",          "data_species_regions",
  "10.1",                                                     "10.1 Future prospects of parameters",        "data_species_regions",
  "10.2",                                                             "10.2 Additional information",        "data_species_regions",
  "11.1",                                                                              "11.1 Range",        "data_species_regions",
  "11.2",                                                                         "11.2 Population",        "data_species_regions",
  "11.3",                                                            "11.3 Habitat for the species",        "data_species_regions",
  "11.4",                                                                   "11.4 Future prospects",        "data_species_regions",
  "11.5",                                          "11.5 Overall assessment of Conservation Status",        "data_species_regions",
  "11.6",                                               "11.6 Overall trend in Conservation Status",        "data_species_regions",
  "11.7", "11.7 Change and reasons for change in conservation status and conservation status trend",                "data_species_regions",
  "11.8",                                                             "11.8 Additional information",        "data_species_regions",
  "12.1",                            "12.1 Population size inside the pSCIs, SCIs and SACs network",        "data_species_regions",
  "12.2",                                                                   "12.2 Type of estimate",        "data_species_regions",
  "12.3",                                    "12.3 Population size inside the network; Method used",        "data_species_regions",
  "12.4",              "12.4 Short term trend of the population size within the network; Direction",        "data_species_regions",
  "12.5",                "12.5 Short term trend of population size within the network; Method used",        "data_species_regions",
  "12.6",                                                             "12.6 Additional information",        "data_species_regions",
  "13.1",                                           "13.1 Justification of 1% threshold for trends",        "data_species_regions",
  "13.2",                                                          "13.2 Trans-boundary assessment",        "data_species_regions",
  "13.3",                                                         "13.3 Other relevant information",        "data_species_regions"
)

# notes_habitat_look_up
notes_habitat_look_up <- tibble::tribble(
  ~reporting_code,                                                                                ~field_label,            ~entity_table_name,
  "2.1",                                                                       "2.1 Year or period",               "data_habitats",
  "2.2",                                                                     "2.2 Distribution map",               "data_habitats",
  "2.3",                                                        "2.3 Distribution map; Method used",               "data_habitats",
  "2.4",                                                                      "2.4 Additional maps",               "data_habitats",
  "3.1",                              "3.1 Biogeographic or marine region where the habitat occurs",    "data_habitattype_regions",
  "3.2",                                                               "3.2 Sources of information",    "data_habitattype_regions",
  "4.1",                                                                         "4.1 Surface area",    "data_habitattype_regions",
  "4.2",                                                             "4.2 Short term trend; Period",    "data_habitattype_regions",
  "4.3",                                                          "4.3 Short term trend; Direction",    "data_habitattype_regions",
  "4.4",                                                          "4.4 Short term trend; Magnitude",    "data_habitattype_regions",
  "4.5",                                                        "4.5 Short term trend; Method used",    "data_habitattype_regions",
  "4.6",                                                              "4.6 Long term trend; Period",    "data_habitattype_regions",
  "4.7",                                                           "4.7 Long term trend; Direction",    "data_habitattype_regions",
  "4.8",                                                           "4.8 Long term trend; Magnitude",    "data_habitattype_regions",
  "4.9",                                                         "4.9 Long term trend; Method used",    "data_habitattype_regions",
  "4.10",                                                           "4.10 Favourable reference range",    "data_habitattype_regions",
  "4.11",                               "4.11 Change and reason for change in surface area of range",                 "data_habitattype_regions",
  "4.12",                                                              "4.12 Additional information",    "data_habitattype_regions",
  "5.1",                                                                       "5.1 Year or period",    "data_habitattype_regions",
  "5.2",                                                                         "5.2 Surface area",    "data_habitattype_regions",
  "5.3",                                                                     "5.3 Type of estimate",    "data_habitattype_regions",
  "5.4",                                                            "5.4 Surface area; Method used",    "data_habitattype_regions",
  "5.5",                                                             "5.5 Short term trend; Period",    "data_habitattype_regions",
  "5.6",                                                          "5.6 Short term trend; Direction",    "data_habitattype_regions",
  "5.7",                                                          "5.7 Short term trend; Magnitude",    "data_habitattype_regions",
  "5.8",                                                        "5.8 Short term trend; Method used",    "data_habitattype_regions",
  "5.9",                                                              "5.9 Long term trend; Period",    "data_habitattype_regions",
  "5.10",                                                           "5.10 Long term trend; Direction",    "data_habitattype_regions",
  "5.11",                                                          "5.11 Long term trend; Magnitude",    "data_habitattype_regions",
  "5.12",                                                        "5.12 Long term trend; Method used",    "data_habitattype_regions",
  "5.13",                                                           "5.13 Favourable reference area",    "data_habitattype_regions",
  "5.14",                                        "5.14 Change and reason for change in surface area",                 "data_habitattype_regions",
  "5.15",                                                              "5.15 Additional information",    "data_habitattype_regions",
  "6.1",                                                                 "6.1 Condition of habitat",    "data_habitattype_regions",
  "6.2",                                                    "6.2 Condition of habitat; Method used",    "data_habitattype_regions",
  "6.3",                           "6.3 Short term trend of habitat area in good condition; Period",    "data_habitattype_regions",
  "6.4",                        "6.4 Short term trend of habitat area in good condition; Direction",    "data_habitattype_regions",
  "6.5",                      "6.5 Short term trend of habitat area in good condition; Method used",    "data_habitattype_regions",
  "6.6",                                                                      "6.6 Typical species",    "data_habitattype_regions",
  "6.7",                                                          "6.7 Typical speces; Method used",    "data_habitattype_regions",
  "6.8",                                                               "6.8 Additional information",    "data_habitattype_regions",
  "7.1",                                               "7.1 Characterisation of pressures/ threats",      "data_habitattype_regions",
  "7.2",                                                               "7.2 Sources of information", "data_habitattype_regions",
  "7.3",                                                               "7.3 Additional information", "data_habitattype_regions",
  "8.1",                                                                   "8.1 Status of measures",          "data_habitattype_regions",
  "8.2",                                                   "8.2 Main purpose of the measures taken",          "data_habitattype_regions",
  "8.3",                                                       "8.3 Location of the measures taken",          "data_habitattype_regions",
  "8.4",                                                             "8.4 Response to the measures",          "data_habitattype_regions",
  "8.5",                                                   "8.5 List of main conservation measures",               "data_habitattype_regions",
  "8.6",                                                               "8.6 Additional information",          "data_habitattype_regions",
  "9.1",                                                       "9.1 Future prospects of parameters",    "data_habitattype_regions",
  "9.2",                                                               "9.2 Additional information",    "data_habitattype_regions",
  "10.1",                                                                               "10.1 Range",    "data_habitattype_regions",
  "10.2",                                                                                "10.2 Area",    "data_habitattype_regions",
  "10.3",                                                    "10.3 Specific structure and functions",    "data_habitattype_regions",
  "10.4",                                                                    "10.4 Future prospects",    "data_habitattype_regions",
  "10.5",                                           "10.5 Overall assessment of Conservation Status",    "data_habitattype_regions",
  "10.6",                                                 "10.6 Overal trend in Conservation Status",    "data_habitattype_regions",
  "10.7", "10.7 Change and reasons for change in conservation status and conservation status trends",                 "data_habitattype_regions",
  "10.8",                                                              "10.8 Additional information",    "data_habitattype_regions",
  "11.1",             "11.1 Surface area of the habitat type inside the pSCIs, SCIs and SACs network",    "data_habitattype_regions",
  "11.2",                                                                    "11.2 Type of estimate",    "data_habitattype_regions",
  "11.3",                    "11.3 Surface area of the habitat type inside the network; Method used",    "data_habitattype_regions",
  "11.4",    "11.4 Short term trend of habitat area in good condition within the network; Direction",    "data_habitattype_regions",
  "11.5",  "11.5 Short term trend of habitat area in good condition within the network; Method used",    "data_habitattype_regions",
  "11.6",                                                              "11.6 Additional information",    "data_habitattype_regions",
  "12.1",                                            "12.1 Justification of 1% threshold for trends",    "data_habitattype_regions",
  "12.2",                                                          "12.2 Other relevant information",    "data_habitattype_regions"
)

# information_species_look_up
information_species_look_up <- readxl::read_excel("./Range mapping/Lookups/species_lookup_tables_2019.xlsx") %>%
  dplyr::filter(!is.na(alpha))

# information_habitat_look_up
information_habitat_look_up <- readxl::read_excel("./Range mapping/Lookups/habitat_lookup_tables_2019.xlsx") %>%
  dplyr::filter(!is.na(alpha))


